spring:
 datasource:
  url: jdbc:mysql://localhost:3306/librarydb?createDatabaseIfNotExist=true
  username: root
  password: Shiva_123
 jpa:
  hibernate.ddl-auto: update
  show-sql: true
  
server:
 port: 8080
 
book:
 permissibleDays:14
